# Example Sound FX Configuration
# This demonstrates the proposed YAML configuration format

version: "1.0"

metadata:
  name: "Default Cat FX Pack"
  description: "Original cat sound library for GitHub activity soundtrack"
  author: "bots-n-cats"
  version: "1.0.0"
  created: "2024-01-01"
  tags:
    - cats
    - organic
    - playful

# Individual sound definitions
sounds:
  # ============================================================================
  # RHYTHMIC/PERCUSSIVE (for beats and rhythm)
  # ============================================================================
  
  purr_c2:
    name: "Deep Bass Purr"
    category: rhythmic
    pitch: C2
    bpm: 120
    duration: 2.0
    loopable: true
    emotion: resolution
    description: "Deep, resonant purr for bass line foundation"
    file: null  # Future: path to actual audio file
    tags:
      - bass
      - low-frequency
      - foundation

  purr_c3:
    name: "Mid-Range Purr"
    category: rhythmic
    pitch: C3
    bpm: 130
    duration: 2.0
    loopable: true
    emotion: resolution
    description: "Medium purr for rhythmic texture"
    file: null
    tags:
      - mid-range
      - rhythmic

  purr_ambient:
    name: "Ambient Purr Pad"
    category: rhythmic
    bpm: 120
    duration: 4.0
    loopable: true
    emotion: resolution
    description: "Long, sustained purr for ambient padding"
    file: null
    tags:
      - ambient
      - pad
      - sustained

  chirp_percussion:
    name: "Percussion Chirp"
    category: rhythmic
    duration: 0.15
    loopable: false
    emotion: activity
    description: "Short, sharp chirp for hi-hat patterns"
    file: null
    tags:
      - percussion
      - short
      - hi-hat

  chirp_double:
    name: "Double Chirp"
    category: rhythmic
    duration: 0.25
    loopable: false
    emotion: activity
    description: "Two quick chirps for snare-like hits"
    file: null
    tags:
      - percussion
      - snare

  breathing_slow:
    name: "Slow Breathing"
    category: rhythmic
    bpm: 60
    duration: 3.0
    loopable: true
    emotion: resolution
    description: "Gentle breathing for ambient texture"
    file: null

  paw_tap_soft:
    name: "Soft Paw Tap"
    category: rhythmic
    duration: 0.1
    loopable: false
    emotion: activity
    description: "Subtle paw tap for gentle percussion"
    file: null

  paw_tap_double:
    name: "Double Paw Tap"
    category: rhythmic
    duration: 0.2
    loopable: false
    emotion: activity
    description: "Two quick paw taps for rhythm"
    file: null

  # ============================================================================
  # MELODIC (for musical phrases)
  # ============================================================================
  
  meow_c4:
    name: "Meow - C4"
    category: melodic
    pitch: C4
    duration: 0.5
    loopable: false
    emotion: activity
    description: "Musical meow tuned to C4"
    file: null

  meow_d4:
    name: "Meow - D4"
    category: melodic
    pitch: D4
    duration: 0.5
    loopable: false
    emotion: activity
    description: "Musical meow tuned to D4"
    file: null

  meow_e4:
    name: "Meow - E4"
    category: melodic
    pitch: E4
    duration: 0.5
    loopable: false
    emotion: activity
    description: "Musical meow tuned to E4"
    file: null

  meow_f4:
    name: "Meow - F4"
    category: melodic
    pitch: F4
    duration: 0.5
    loopable: false
    emotion: activity
    description: "Musical meow tuned to F4"
    file: null

  meow_g4:
    name: "Meow - G4"
    category: melodic
    pitch: G4
    duration: 0.5
    loopable: false
    emotion: activity
    description: "Musical meow tuned to G4"
    file: null

  meow_a4:
    name: "Meow - A4"
    category: melodic
    pitch: A4
    duration: 0.5
    loopable: false
    emotion: activity
    description: "Musical meow tuned to A4"
    file: null

  meow_b4:
    name: "Meow - B4"
    category: melodic
    pitch: B4
    duration: 0.5
    loopable: false
    emotion: activity
    description: "Musical meow tuned to B4"
    file: null

  trill_c5:
    name: "Cat Trill - C5"
    category: melodic
    pitch: C5
    duration: 0.8
    loopable: false
    emotion: resolution
    description: "Melodic cat trill, high register"
    file: null

  trill_g4:
    name: "Cat Trill - G4"
    category: melodic
    pitch: G4
    duration: 0.8
    loopable: false
    emotion: resolution
    description: "Melodic cat trill, mid register"
    file: null

  question_meow:
    name: "Question Meow"
    category: melodic
    pitch: E4
    duration: 0.6
    loopable: false
    emotion: tension
    description: "Rising pitch contour meow (questioning)"
    file: null

  content_meow:
    name: "Content Meow"
    category: melodic
    pitch: C4
    duration: 0.7
    loopable: false
    emotion: resolution
    description: "Falling pitch contour meow (satisfied)"
    file: null

  # ============================================================================
  # TEXTURAL (for ambiance and pads)
  # ============================================================================
  
  gentle_purr_pad:
    name: "Gentle Purr Pad"
    category: textural
    duration: 5.0
    loopable: true
    emotion: resolution
    description: "Long sustain purr for ambient pads"
    file: null

  kneading_rhythm:
    name: "Kneading Rhythm"
    category: textural
    bpm: 80
    duration: 2.0
    loopable: true
    emotion: resolution
    description: "Rhythmic kneading sound texture"
    file: null

  grooming_ambient:
    name: "Grooming Ambiance"
    category: textural
    duration: 3.0
    loopable: true
    emotion: resolution
    description: "Quiet grooming sounds for background"
    file: null

  sleepy_sigh:
    name: "Sleepy Sigh"
    category: textural
    duration: 1.5
    loopable: false
    emotion: resolution
    description: "Peaceful sigh for resolution moments"
    file: null

  stretch_yawn:
    name: "Stretch Yawn"
    category: textural
    duration: 2.0
    loopable: false
    emotion: resolution
    description: "Content stretch with yawn"
    file: null

  # ============================================================================
  # EXPRESSIVE (for specific events)
  # ============================================================================
  
  excited_chirp:
    name: "Excited Chirp"
    category: expressive
    duration: 0.3
    loopable: false
    emotion: activity
    description: "Excited chirp for features/deploys"
    file: null

  happy_chirp_sequence:
    name: "Happy Chirp Sequence"
    category: expressive
    duration: 1.0
    loopable: false
    emotion: resolution
    description: "Series of happy chirps for success"
    file: null

  playful_meow:
    name: "Playful Meow"
    category: expressive
    duration: 0.4
    loopable: false
    emotion: activity
    description: "Playful meow for commits/activity"
    file: null

  gentle_chirp:
    name: "Gentle Chirp"
    category: expressive
    duration: 0.2
    loopable: false
    emotion: activity
    description: "Soft chirp for minor events"
    file: null

  disappointed_mrrp:
    name: "Disappointed Mrrp"
    category: expressive
    duration: 0.5
    loopable: false
    emotion: tension
    description: "Gentle disappointed sound for conflicts"
    file: null

  tiny_hiss:
    name: "Tiny Hiss"
    category: expressive
    duration: 0.3
    loopable: false
    emotion: tension
    description: "Very subtle hiss for test failures (musical)"
    file: null

  curious_trill:
    name: "Curious Trill"
    category: expressive
    duration: 0.6
    loopable: false
    emotion: growth
    description: "Curious trill for new features"
    file: null

  satisfied_purr_burst:
    name: "Satisfied Purr Burst"
    category: expressive
    duration: 1.0
    loopable: false
    emotion: resolution
    description: "Happy purr burst for completed work"
    file: null

# Precomputed lookups for performance
# These avoid runtime filtering
categories:
  rhythmic:
    - purr_c2
    - purr_c3
    - purr_ambient
    - chirp_percussion
    - chirp_double
    - breathing_slow
    - paw_tap_soft
    - paw_tap_double
  
  melodic:
    - meow_c4
    - meow_d4
    - meow_e4
    - meow_f4
    - meow_g4
    - meow_a4
    - meow_b4
    - trill_c5
    - trill_g4
    - question_meow
    - content_meow
  
  textural:
    - gentle_purr_pad
    - kneading_rhythm
    - grooming_ambient
    - sleepy_sigh
    - stretch_yawn
  
  expressive:
    - excited_chirp
    - happy_chirp_sequence
    - playful_meow
    - gentle_chirp
    - disappointed_mrrp
    - tiny_hiss
    - curious_trill
    - satisfied_purr_burst

# Sampler mappings for musical instruments
melodic_samples:
  C4: meow_c4
  D4: meow_d4
  E4: meow_e4
  F4: meow_f4
  G4: meow_g4
  A4: meow_a4
  B4: meow_b4
  C5: trill_c5

purr_samples:
  C2: purr_c2
  C3: purr_c3

# Configuration metadata
config:
  allow_custom_sounds: true
  require_validation: true
  cache_duration: 3600  # seconds
  hot_reload_in_dev: true
